/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "surface-container-low": "#131317",
        "on-secondary": "#005745",
        "primary": "#a8a4ff",
        "secondary-fixed-dim": "#33e5ba",
        "inverse-on-surface": "#555459",
        "primary-container": "#9995ff",
        "background": "#0e0e12",
        "secondary-dim": "#33e5ba",
        "on-surface-variant": "#acaab0",
        "surface-container-highest": "#25252b",
        "on-tertiary-container": "#310003",
        "secondary": "#49f4c8",
        "primary-fixed": "#9995ff",
        "on-error": "#490013",
        "surface-container": "#19191e",
        "error-container": "#a70138",
        "surface-variant": "#25252b",
        "surface-container-high": "#1f1f24",
        "on-primary": "#1e009f",
        "primary-fixed-dim": "#8a85ff",
        "secondary-container": "#006b55",
        "on-secondary-container": "#dffff1",
        "error-dim": "#d73357",
        "surface-bright": "#2c2b32",
        "surface-tint": "#a8a4ff",
        "tertiary-fixed-dim": "#ff7b77",
        "tertiary-container": "#fe5b5b",
        "secondary-fixed": "#49f4c8",
        "primary-dim": "#675df9",
        "on-primary-fixed": "#000000",
        "outline-variant": "#48474c",
        "surface-dim": "#0e0e12",
        "on-error-container": "#ffb2b9",
        "tertiary-dim": "#ff706d",
        "surface": "#0e0e12",
        "error": "#ff6e84",
        "outline": "#76757a",
        "inverse-surface": "#fcf8fe",
        "on-background": "#fcf8fe",
        "on-primary-container": "#16007d",
        "inverse-primary": "#5044e3",
        "tertiary": "#ff7672",
        "on-surface": "#fcf8fe",
        "admin-accent": "#FF8C42",
        "on-tertiary": "#4e0008",
        "on-primary-fixed-variant": "#1d0098",
      },
      fontFamily: {
        "headline": ["'Bricolage Grotesque'", "sans-serif"],
        "body": ["'DM Sans'", "sans-serif"],
        "label": ["'DM Sans'", "sans-serif"],
        "mono": ["'JetBrains Mono'", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
